services:
  db:
    container_name: prepopulated-db-container
    image: prepopulated-db-image
    networks:
      - custom-network
    ports:
      - "3306:3306"

networks:
  custom-network:
    name: custom-network
