services:
  ui:
    container_name: react-ui-container
    image: react-ui-image
    networks:
      - custom-network
    ports:
      - "3000:3000"

networks:
  custom-network:
    name: custom-network
